configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal

after_build:
  7z a SerieOrganizer.zip  %APPVEYOR_BUILD_FOLDER%\SerieOrganizer\bin\Release\*.*
  

artifacts:
- path: SerieOrganizer.zip
  name: MyApp
