//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalk.SubtitlesManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chalk.SubtitlesManagement.Resources.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;showid&gt;12934&lt;/showid&gt;
        ///	&lt;tvdbid&gt;84024&lt;/tvdbid&gt;
        ///	&lt;showname&gt;FlashForward&lt;/showname&gt;
        ///	&lt;showlink&gt;http://www.bierdopje.com/shows/flashforward&lt;/showlink&gt;
        ///	&lt;firstaired&gt;24 september 2009 00:00:00&lt;/firstaired&gt;
        ///	&lt;lastaired&gt;22 oktober 2009 00:00:00&lt;/lastaired&gt;
        ///	&lt;nextepisode&gt;12 november 2009 00:00:00&lt;/nextepisode&gt;
        ///	&lt;seasons&gt;1&lt;/seasons&gt;
        ///	&lt;episodes&gt;11&lt;/episodes&gt;
        ///	&lt;genres&gt;
        ///		&lt;result&gt;Drama&lt;/result&gt;
        ///		&lt;result&gt;science-fiction&lt;/result&gt;
        ///
        ///	&lt;/genres&gt;
        ///	&lt;showstatus&gt;Terugkomende serie&lt;/showst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleShowCached {
            get {
                return ResourceManager.GetString("SingleShowCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;showid&gt;12934&lt;/showid&gt;
        ///	&lt;tvdbid&gt;84024&lt;/tvdbid&gt;
        ///	&lt;showname&gt;FlashForward&lt;/showname&gt;
        ///	&lt;showlink&gt;http://www.bierdopje.com/shows/flashforward&lt;/showlink&gt;
        ///	&lt;firstaired&gt;24 september 2009 00:00:00&lt;/firstaired&gt;
        ///	&lt;lastaired&gt;22 oktober 2009 00:00:00&lt;/lastaired&gt;
        ///	&lt;nextepisode&gt;12 november 2009 00:00:00&lt;/nextepisode&gt;
        ///	&lt;seasons&gt;1&lt;/seasons&gt;
        ///	&lt;episodes&gt;11&lt;/episodes&gt;
        ///	&lt;genres&gt;
        ///		&lt;genre&gt;Drama&lt;/genre&gt;
        ///		&lt;genre&gt;science-fiction&lt;/genre&gt;
        ///
        ///	&lt;/genres&gt;
        ///	&lt;showstatus&gt;Terugkomende serie&lt;/showstatus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleShowNotCached {
            get {
                return ResourceManager.GetString("SingleShowNotCached", resourceCulture);
            }
        }
    }
}
