//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4062
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chalk.SubtitlesManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chalk.SubtitlesManagement.Resources.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;true&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;results&gt;
        ///		&lt;result&gt;
        ///			&lt;showid&gt;13673&lt;/showid&gt;
        ///
        ///			&lt;tvdbid&gt;77954&lt;/tvdbid&gt;
        ///			&lt;showname&gt;Flash Forward&lt;/showname&gt;
        ///			&lt;showlink&gt;http://www.bierdopje.com/shows/flash-forward&lt;/showlink&gt;
        ///			&lt;firstaired&gt;1997-01-05&lt;/firstaired&gt;
        ///			&lt;lastaired&gt;1997-01-05&lt;/lastaired&gt;
        ///			&lt;nextepisode&gt;&lt;/nextepisode&gt;
        ///
        ///			&lt;seasons&gt;1&lt;/seasons&gt;
        ///			&lt;episodes&gt;0&lt;/episodes&gt;
        ///			&lt;genres&gt;
        ///				&lt;resul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindShowsByNameCached {
            get {
                return ResourceManager.GetString("FindShowsByNameCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;false&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;results&gt;
        ///		&lt;result&gt;
        ///			&lt;showid&gt;13673&lt;/showid&gt;
        ///
        ///			&lt;tvdbid&gt;77954&lt;/tvdbid&gt;
        ///			&lt;showname&gt;Flash Forward&lt;/showname&gt;
        ///			&lt;showlink&gt;http://www.bierdopje.com/shows/flash-forward&lt;/showlink&gt;
        ///			&lt;firstaired&gt;1997-01-05&lt;/firstaired&gt;
        ///			&lt;lastaired&gt;1997-01-05&lt;/lastaired&gt;
        ///			&lt;nextepisode&gt;&lt;/nextepisode&gt;
        ///
        ///			&lt;seasons&gt;1&lt;/seasons&gt;
        ///			&lt;episodes&gt;0&lt;/episodes&gt;
        ///			&lt;genres&gt;
        ///				&lt;resu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindShowsByNameNotCached {
            get {
                return ResourceManager.GetString("FindShowsByNameNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;false&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;cachelife&gt;1281546573&lt;/cachelife&gt;
        ///	&lt;results&gt;
        ///
        ///		&lt;result&gt;
        ///			&lt;episodeid&gt;449199&lt;/episodeid&gt;
        ///			&lt;tvdbid&gt;266088&lt;/tvdbid&gt;
        ///			&lt;title&gt;Fresh Start All Over Again&lt;/title&gt;
        ///			&lt;showlink&gt;http://www.bierdopje.com/shows/flash-forward&lt;/showlink&gt;
        ///			&lt;episodelink&gt;http://www.bierdopje.com/shows/flash-forward/episode/S01E01&lt;/episodelink&gt;
        ///
        ///			&lt;season&gt;1&lt;/season&gt;
        ///			&lt;episode&gt;1&lt;/epis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllEpisodesForShowCached {
            get {
                return ResourceManager.GetString("GetAllEpisodesForShowCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;false&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;cachelife&gt;1281546573&lt;/cachelife&gt;
        ///	&lt;results&gt;
        ///
        ///		&lt;result&gt;
        ///			&lt;episodeid&gt;449199&lt;/episodeid&gt;
        ///			&lt;tvdbid&gt;266088&lt;/tvdbid&gt;
        ///			&lt;title&gt;Fresh Start All Over Again&lt;/title&gt;
        ///			&lt;showlink&gt;http://www.bierdopje.com/shows/flash-forward&lt;/showlink&gt;
        ///			&lt;episodelink&gt;http://www.bierdopje.com/shows/flash-forward/episode/S01E01&lt;/episodelink&gt;
        ///
        ///			&lt;season&gt;1&lt;/season&gt;
        ///			&lt;episode&gt;1&lt;/epis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllEpisodesForShowNotCached {
            get {
                return ResourceManager.GetString("GetAllEpisodesForShowNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;true&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;results&gt;
        ///		&lt;result&gt;
        ///			&lt;filename&gt;flash.forward.s01e01.hdtv.xvid-2hd&lt;/filename&gt;
        ///
        ///			&lt;filesize&gt;40801&lt;/filesize&gt;
        ///			&lt;uploader&gt;roelschilderman&lt;/uploader&gt;
        ///			&lt;uploaderprofile&gt;http://www.bierdopje.com/users/roelschilderman/profile&lt;/uploaderprofile&gt;
        ///			&lt;pubdate&gt;1277588133&lt;/pubdate&gt;
        ///			&lt;numreplies&gt;0&lt;/numreplies&gt;
        ///			&lt;numdownloads&gt;116&lt;/numdownloads&gt;
        ///
        ///			&lt;exclusive&gt;false&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllSubsForEpisodeCached {
            get {
                return ResourceManager.GetString("GetAllSubsForEpisodeCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;false&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;results&gt;
        ///		&lt;result&gt;
        ///			&lt;filename&gt;flash.forward.s01e01.hdtv.xvid-2hd&lt;/filename&gt;
        ///
        ///			&lt;filesize&gt;40801&lt;/filesize&gt;
        ///			&lt;uploader&gt;roelschilderman&lt;/uploader&gt;
        ///			&lt;uploaderprofile&gt;http://www.bierdopje.com/users/roelschilderman/profile&lt;/uploaderprofile&gt;
        ///			&lt;pubdate&gt;1277588133&lt;/pubdate&gt;
        ///			&lt;numreplies&gt;0&lt;/numreplies&gt;
        ///			&lt;numdownloads&gt;116&lt;/numdownloads&gt;
        ///
        ///			&lt;exclusive&gt;false [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllSubsForEpisodeNotCached {
            get {
                return ResourceManager.GetString("GetAllSubsForEpisodeNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;episodeid&gt;418319&lt;/episodeid&gt;
        ///	&lt;tvdbid&gt;428750&lt;/tvdbid&gt;
        ///	&lt;showname&gt;FlashForward&lt;/showname&gt;
        ///	&lt;title&gt;No More Good Days&lt;/title&gt;
        ///	&lt;episodelink&gt;http://www.bierdopje.com/shows/flashforward/episode/S01E01&lt;/episodelink&gt;
        ///	&lt;season&gt;1&lt;/season&gt;
        ///	&lt;episode&gt;1&lt;/episode&gt;
        ///	&lt;epnumber&gt;1&lt;/epnumber&gt;
        ///	&lt;wip&gt;true&lt;/wip&gt;
        ///	&lt;wippercentage&gt;100&lt;/wippercentage&gt;
        ///	&lt;wipuser&gt;rickth64&lt;/wipuser&gt;
        ///	&lt;score&gt;9,71&lt;/score&gt;
        ///	&lt;votes&gt;7&lt;/votes&gt;
        ///	&lt;airdate&gt;24-09-2009&lt;/airdate&gt;
        ///	&lt;formatted&gt;S01E01&lt;/formatted&gt;
        ///	&lt;is_special&gt;false&lt;/is_speci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEpisodeByIdCached {
            get {
                return ResourceManager.GetString("GetEpisodeByIdCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;episodeid&gt;418319&lt;/episodeid&gt;
        ///	&lt;tvdbid&gt;428750&lt;/tvdbid&gt;
        ///	&lt;showname&gt;FlashForward&lt;/showname&gt;
        ///	&lt;title&gt;No More Good Days&lt;/title&gt;
        ///	&lt;episodelink&gt;http://www.bierdopje.com/shows/flashforward/episode/S01E01&lt;/episodelink&gt;
        ///	&lt;season&gt;1&lt;/season&gt;
        ///	&lt;episode&gt;1&lt;/episode&gt;
        ///	&lt;epnumber&gt;1&lt;/epnumber&gt;
        ///	&lt;wip&gt;true&lt;/wip&gt;
        ///	&lt;wippercentage&gt;100&lt;/wippercentage&gt;
        ///	&lt;wipuser&gt;rickth64&lt;/wipuser&gt;
        ///	&lt;score&gt;9,71&lt;/score&gt;
        ///	&lt;votes&gt;7&lt;/votes&gt;
        ///	&lt;airdate&gt;24-09-2009&lt;/airdate&gt;
        ///	&lt;formatted&gt;S01E01&lt;/formatted&gt;
        ///	&lt;is_special&gt;false&lt;/is_speci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEpisodeByIdNotCached {
            get {
                return ResourceManager.GetString("GetEpisodeByIdNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;true&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;results&gt;
        ///		&lt;result&gt;
        ///			&lt;episodeid&gt;449199&lt;/episodeid&gt;
        ///
        ///			&lt;tvdbid&gt;266088&lt;/tvdbid&gt;
        ///			&lt;title&gt;Fresh Start All Over Again&lt;/title&gt;
        ///			&lt;showlink&gt;http://www.bierdopje.com/shows/flash-forward&lt;/showlink&gt;
        ///			&lt;episodelink&gt;http://www.bierdopje.com/shows/flash-forward/episode/S01E01&lt;/episodelink&gt;
        ///			&lt;season&gt;1&lt;/season&gt;
        ///			&lt;episode&gt;1&lt;/episode&gt;
        ///
        ///			&lt;epnumber&gt;1&lt;/epnumber&gt;
        ///			&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEpisodesForSeasonCached {
            get {
                return ResourceManager.GetString("GetEpisodesForSeasonCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;status&gt;true&lt;/status&gt;
        ///	&lt;cached&gt;false&lt;/cached&gt;
        ///	&lt;apiversion&gt;201003031200&lt;/apiversion&gt;
        ///	&lt;cachelife&gt;1281547956&lt;/cachelife&gt;
        ///	&lt;results&gt;
        ///
        ///		&lt;result&gt;
        ///			&lt;episodeid&gt;449199&lt;/episodeid&gt;
        ///			&lt;tvdbid&gt;266088&lt;/tvdbid&gt;
        ///			&lt;title&gt;Fresh Start All Over Again&lt;/title&gt;
        ///			&lt;showlink&gt;http://www.bierdopje.com/shows/flash-forward&lt;/showlink&gt;
        ///			&lt;episodelink&gt;http://www.bierdopje.com/shows/flash-forward/episode/S01E01&lt;/episodelink&gt;
        ///
        ///			&lt;season&gt;1&lt;/season&gt;
        ///			&lt;episode&gt;1&lt;/epis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEpisodesForSeasonNotCached {
            get {
                return ResourceManager.GetString("GetEpisodesForSeasonNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;showid&gt;12934&lt;/showid&gt;
        ///	&lt;tvdbid&gt;84024&lt;/tvdbid&gt;
        ///	&lt;showname&gt;FlashForward&lt;/showname&gt;
        ///	&lt;showlink&gt;http://www.bierdopje.com/shows/flashforward&lt;/showlink&gt;
        ///	&lt;firstaired&gt;24 september 2009 00:00:00&lt;/firstaired&gt;
        ///	&lt;lastaired&gt;22 oktober 2009 00:00:00&lt;/lastaired&gt;
        ///	&lt;nextepisode&gt;12 november 2009 00:00:00&lt;/nextepisode&gt;
        ///	&lt;seasons&gt;1&lt;/seasons&gt;
        ///	&lt;episodes&gt;11&lt;/episodes&gt;
        ///	&lt;genres&gt;
        ///		&lt;result&gt;Drama&lt;/result&gt;
        ///		&lt;result&gt;science-fiction&lt;/result&gt;
        ///
        ///	&lt;/genres&gt;
        ///	&lt;showstatus&gt;Terugkomende serie&lt;/showstatus&gt;
        ///	&lt;network&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleShowCached {
            get {
                return ResourceManager.GetString("SingleShowCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;bierdopje&gt;
        ///&lt;response&gt;
        ///	&lt;showid&gt;12934&lt;/showid&gt;
        ///	&lt;tvdbid&gt;84024&lt;/tvdbid&gt;
        ///	&lt;showname&gt;FlashForward&lt;/showname&gt;
        ///	&lt;showlink&gt;http://www.bierdopje.com/shows/flashforward&lt;/showlink&gt;
        ///	&lt;firstaired&gt;24 september 2009 00:00:00&lt;/firstaired&gt;
        ///	&lt;lastaired&gt;22 oktober 2009 00:00:00&lt;/lastaired&gt;
        ///	&lt;nextepisode&gt;12 november 2009 00:00:00&lt;/nextepisode&gt;
        ///	&lt;seasons&gt;1&lt;/seasons&gt;
        ///	&lt;episodes&gt;11&lt;/episodes&gt;
        ///	&lt;genres&gt;
        ///		&lt;genre&gt;Drama&lt;/genre&gt;
        ///		&lt;genre&gt;science-fiction&lt;/genre&gt;
        ///
        ///	&lt;/genres&gt;
        ///	&lt;showstatus&gt;Terugkomende serie&lt;/showstatus&gt;
        ///	&lt;network&gt;&lt;/ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleShowNotCached {
            get {
                return ResourceManager.GetString("SingleShowNotCached", resourceCulture);
            }
        }
    }
}
