//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4062
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Chalk.SubtitlesManagement {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/OrganisationConfiguration.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("SubtitlesConfiguration", Namespace="http://tempuri.org/OrganisationConfiguration.xsd", IsNullable=false)]
    public partial class SubtitlesConfigurationType {
        
        private string bierdopjeApiKeyField;
        
        private string bierdopjeUrlField;
        
        /// <remarks/>
        public string BierdopjeApiKey {
            get {
                return this.bierdopjeApiKeyField;
            }
            set {
                this.bierdopjeApiKeyField = value;
            }
        }
        
        /// <remarks/>
        public string BierdopjeUrl {
            get {
                return this.bierdopjeUrlField;
            }
            set {
                this.bierdopjeUrlField = value;
            }
        }
    }
}
