//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Chalk.SerieOrganizer {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/OrganisationConfiguration.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("OrganisationConfiguration", Namespace="http://tempuri.org/OrganisationConfiguration.xsd", IsNullable=false)]
    public partial class OrganisationConfigurationType {
        
        private string destinationDirectoryField;
        
        private string directoryToOrganizeField;
        
        private string unrecognizedDirectoryField;
        
        /// <remarks/>
        public string DestinationDirectory {
            get {
                return this.destinationDirectoryField;
            }
            set {
                this.destinationDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string DirectoryToOrganize {
            get {
                return this.directoryToOrganizeField;
            }
            set {
                this.directoryToOrganizeField = value;
            }
        }
        
        /// <remarks/>
        public string UnrecognizedDirectory {
            get {
                return this.unrecognizedDirectoryField;
            }
            set {
                this.unrecognizedDirectoryField = value;
            }
        }
    }
}
