//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowConversionTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShowConversionTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShowConversionTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShowConversionTest.ShowConversionTest", typeof(ShowConversionTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rdf:RDF xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot; xmlns:tv=&quot;http://www.semanticarchitecture.net/tv#&quot;&gt;
        ///   &lt;tv:Show rdf:about=&quot;http://www.semanticarchitecture.net/TvShow.rdf@Show1&quot;&gt;
        ///      &lt;tv:AirTime&gt;12&lt;/tv:AirTime&gt;
        ///      &lt;tv:Favorites&gt;1&lt;/tv:Favorites&gt;
        ///      &lt;tv:FirstAired&gt;01/10/12/2010T10:10:10&lt;/tv:FirstAired&gt;
        ///      &lt;tv:Genre&gt;Thriller&lt;/tv:Genre&gt;
        ///      &lt;tv:Genre&gt;Comedy&lt;/tv:Genre&gt;
        ///      &lt;tv:HasTranslators&gt;Yes&lt;/tv:HasTranslators&gt;
        ///      &lt;tv:Id&gt;1&lt;/tv:Id&gt;
        ///      &lt;tv:Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertedRDFFromShow {
            get {
                return ResourceManager.GetString("ConvertedRDFFromShow", resourceCulture);
            }
        }
    }
}
